vich_uploader:
    db_driver: orm

    mappings:
        file:
           uri_prefix: /upload/image/artwork
           upload_destination: '%kernel.project_dir%/public/upload/image/artwork'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
